### ISSUE TITLE
A concern regarding sub brach being too different to merge

### ISSUE THREAD

**Issue by EliWangC** [Faye-yufan/analytics-dataset#22]
Recently we've been working on branch `github-actions` and now it's '14 commits ahead, 3 commits behind main'. I was wondering wouldn't it be very tricky to resolve the conflicts when we merge them?
I would love to hear someone's opinions on how to merge a very different sub branch to the main branch!

**Comment by Faye-yufan** [comment]
I agree, it would be very tricky to merge if we have too many changes on each branch.
I think, for now, it's not that hard to merge #17 . However, as for refactoring, it might be difficult to merge #21  after #17 is merged. Maybe I will open another branch for refactoring based on the new `main` branch.

**Comment by Faye-yufan** [comment]
I just resolved some conflicts on the recent PR. Here are some new experiences: 
1. From now on, I think the GH Actions would be a great standard for resolving the conflicts, i.e., once all of them passed, it means it's good to move forward.
2. VSCode has a great tool for checking out merging conflicts, but I'm sure other text editors are also able to do that. Here is what I did with command line and VSCode:
   - `git pull origin main`
   - `git checkout github-actions` (here _github-actions_ is the branch name)
   - `git merge main`
   - start editing on VSCode, resolving all the conflicts, and commit the changes
   - `git push -u origin github-actions`

**Comment by EliWangC** [comment]
Great insights! Thank you Fei. I'll implement the conflict-solving tool in VSCode too.
Just a quick question: Are the 'GH Actions' you mentioned our unit tests? How are they related to resolving conflicts between two branches?

**Comment by Faye-yufan** [comment]
Yes, GH Actions includes our unit tests.
So after one resolving some conflicts, the gh action will run again to
check the code, since the ‘resolving’ itself is a push. If all the tests
(inside gh actions) passed, it means to some extent, all the
functionalities works fine and conflicts were successfully ‘resolved’.

**Comment by Faye-yufan** [comment]
Here are some main steps we can follow:
1. Update local main branch to the latest version: `git checkout main` -> `git pull origin main`
2. Rebase the feature branch on main branch: `git checkout feature-branch` -> `git rebase main`
3. Resolve conflicts: Git will give a message saying which files are causing the conflict. Open those files and look for the conflict markers (<<<<<<, ======, and >>>>>>). The code between <<<<<< and ====== is your/new code, and the code between ====== and >>>>>> is from the branch you're rebasing onto. Decide which code to keep, delete the conflict markers, and then save the file.
4. `git add <those files>` -> `git rebase --continue`
5. Push the changes: `git push origin feature-branch`

Also, a great article discussing about this issue: https://www.freecodecamp.org/news/resolve-merge-conflicts-in-git-a-practical-guide/
